package view;

/**
 * Nama : Thessalonica Angelina Meil
 * NPM  : 210711122
 * 
 * Nama : Alexis Divasonda Sigat Ngaing
 * NPM  : 210711407
 */

import control.TenagaMedisControl;
import control.PasienControl;
import control.RekamMedisControl;
import model.TenagaMedis;
import model.Pasien;
import model.RekamMedis;
import table.TableRekamMedis;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import exception.InputKosongException;

public class RekamMedisView extends javax.swing.JFrame {

    private TenagaMedisControl tmControl;
    private PasienControl pControl;
    private RekamMedisControl rmControl;
    
    String action = null;
    int selectedId = 0;
    
    List<TenagaMedis> listTenagaMedis;
    List<Pasien> listPasien;
    
    public RekamMedisView() {
        initComponents();
        setComponent(false);
        setEditDeleteBtn(false);
        tmControl = new TenagaMedisControl();
        pControl = new PasienControl();
        rmControl = new RekamMedisControl();
        showRekamMedis();
        setTenagaMedisToDropdown();
        setPasienToDropdown();
    }
    
    public void setTenagaMedisToDropdown() {
        listTenagaMedis = tmControl.showAllTenagaMedis();
        for (int i = 0; i < listTenagaMedis.size(); i++) {
            tenagaMedisDropdown.addItem(listTenagaMedis.get(i));
        }
    }
    
    public void setPasienToDropdown() {
        listPasien = pControl.showListPasien();
        for (int i = 0; i < listPasien.size(); i++) {
            pasienDropdown.addItem(listPasien.get(i));
        }
    }
    
    public void setComponent(boolean value) {
        tenagaMedisDropdown.setEnabled(value);
        pasienDropdown.setEnabled(value);
        diagnosaInput.setEnabled(value);
        biayaInput.setEnabled(value);
        obatCheckBox.setEnabled(value);
        suntikCheckBox.setEnabled(value);
        konsultasiCheckBox.setEnabled(value);
        
        saveButton.setEnabled(value);
        cancelButton.setEnabled(value);
    }
    
    public void setEditDeleteBtn(boolean value) {
        editButton.setEnabled(value);
        deleteButton.setEnabled(value);
    }
    
    public void clearText() {
        tenagaMedisDropdown.setSelectedIndex(0);
        pasienDropdown.setSelectedIndex(0);
        diagnosaInput.setText("");
        biayaInput.setText("");
        searchInput.setText("");
        obatCheckBox.setSelected(false);
        suntikCheckBox.setSelected(false);
        konsultasiCheckBox.setSelected(false);
    }
    
    public void showRekamMedis() {
        tableRekamMedis.setModel(rmControl.showRekamMedis(""));
    }
    
    public void inputKosongException() throws  InputKosongException {
        if (tenagaMedisDropdown.getSelectedIndex() == -1 
                || pasienDropdown.getSelectedIndex() == -1 
                || diagnosaInput.getText().isEmpty()
                || biayaInput.getText().isEmpty()) {
            throw new InputKosongException();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        containerPanel = new javax.swing.JPanel();
        headerPanel = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        tenagaMedisPanel = new javax.swing.JPanel();
        tenagaMedisIcon = new javax.swing.JLabel();
        tenagaMedisIconLabel = new javax.swing.JLabel();
        rekamMedisPanel = new javax.swing.JPanel();
        rekamMedisIcon = new javax.swing.JLabel();
        rekamMedisIconLabel = new javax.swing.JLabel();
        pasienPanel = new javax.swing.JPanel();
        pasienIcon = new javax.swing.JLabel();
        pasienIconLabel = new javax.swing.JLabel();
        kelompokLabel = new javax.swing.JLabel();
        npmLabel = new javax.swing.JLabel();
        npm2Label = new javax.swing.JLabel();
        menuPanel = new javax.swing.JPanel();
        addButton = new javax.swing.JButton();
        editButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        searchPanel = new javax.swing.JPanel();
        rekamMedisLabel = new javax.swing.JLabel();
        searchButton = new javax.swing.JButton();
        searchInput = new javax.swing.JTextField();
        tenagaMedisLabel = new javax.swing.JLabel();
        tenagaMedisDropdown = new javax.swing.JComboBox<>();
        namaPasienLabel = new javax.swing.JLabel();
        pasienDropdown = new javax.swing.JComboBox<>();
        diagnosaLabel = new javax.swing.JLabel();
        diagnosaInput = new javax.swing.JTextField();
        biayaLabel = new javax.swing.JLabel();
        biayaInput = new javax.swing.JTextField();
        tindakanLabel = new javax.swing.JLabel();
        obatCheckBox = new javax.swing.JCheckBox();
        suntikCheckBox = new javax.swing.JCheckBox();
        konsultasiCheckBox = new javax.swing.JCheckBox();
        cancelButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableRekamMedis = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        containerPanel.setBackground(new java.awt.Color(206, 229, 208));

        headerPanel.setBackground(new java.awt.Color(148, 180, 159));

        titleLabel.setFont(new java.awt.Font("Sitka Small", 1, 36)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(0, 0, 0));
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        titleLabel.setText("RS INTAN MEDIKA");

        tenagaMedisPanel.setBackground(new java.awt.Color(252, 248, 232));
        tenagaMedisPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tenagaMedisPanelMouseClicked(evt);
            }
        });

        tenagaMedisIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets.icons/hospital(2).png"))); // NOI18N

        tenagaMedisIconLabel.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        tenagaMedisIconLabel.setForeground(new java.awt.Color(0, 0, 0));
        tenagaMedisIconLabel.setText("TENAGA MEDIS");

        javax.swing.GroupLayout tenagaMedisPanelLayout = new javax.swing.GroupLayout(tenagaMedisPanel);
        tenagaMedisPanel.setLayout(tenagaMedisPanelLayout);
        tenagaMedisPanelLayout.setHorizontalGroup(
            tenagaMedisPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tenagaMedisPanelLayout.createSequentialGroup()
                .addGroup(tenagaMedisPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tenagaMedisPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(tenagaMedisIconLabel))
                    .addGroup(tenagaMedisPanelLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(tenagaMedisIcon)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        tenagaMedisPanelLayout.setVerticalGroup(
            tenagaMedisPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tenagaMedisPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tenagaMedisIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tenagaMedisIconLabel)
                .addGap(12, 12, 12))
        );

        rekamMedisPanel.setBackground(new java.awt.Color(252, 248, 232));

        rekamMedisIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets.icons/document(1).png"))); // NOI18N
        rekamMedisIcon.setText("rekamMedisIcon");

        rekamMedisIconLabel.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        rekamMedisIconLabel.setForeground(new java.awt.Color(0, 0, 0));
        rekamMedisIconLabel.setText("REKAM MEDIS");

        javax.swing.GroupLayout rekamMedisPanelLayout = new javax.swing.GroupLayout(rekamMedisPanel);
        rekamMedisPanel.setLayout(rekamMedisPanelLayout);
        rekamMedisPanelLayout.setHorizontalGroup(
            rekamMedisPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rekamMedisPanelLayout.createSequentialGroup()
                .addGroup(rekamMedisPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(rekamMedisPanelLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(rekamMedisIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(rekamMedisPanelLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(rekamMedisIconLabel)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        rekamMedisPanelLayout.setVerticalGroup(
            rekamMedisPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rekamMedisPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rekamMedisIcon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rekamMedisIconLabel)
                .addGap(12, 12, 12))
        );

        pasienPanel.setBackground(new java.awt.Color(252, 248, 232));

        pasienIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets.icons/patient(1).png"))); // NOI18N
        pasienIcon.setText("pasienIcon");
        pasienIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pasienIconMouseClicked(evt);
            }
        });

        pasienIconLabel.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        pasienIconLabel.setForeground(new java.awt.Color(0, 0, 0));
        pasienIconLabel.setText("PASIEN");

        javax.swing.GroupLayout pasienPanelLayout = new javax.swing.GroupLayout(pasienPanel);
        pasienPanel.setLayout(pasienPanelLayout);
        pasienPanelLayout.setHorizontalGroup(
            pasienPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pasienPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(pasienPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pasienIconLabel)
                    .addComponent(pasienIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        pasienPanelLayout.setVerticalGroup(
            pasienPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pasienPanelLayout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addComponent(pasienIcon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pasienIconLabel)
                .addGap(12, 12, 12))
        );

        kelompokLabel.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        kelompokLabel.setForeground(new java.awt.Color(0, 0, 0));
        kelompokLabel.setText("KELOMPOK 11");

        npmLabel.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        npmLabel.setForeground(new java.awt.Color(0, 0, 0));
        npmLabel.setText("210711407");

        npm2Label.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        npm2Label.setForeground(new java.awt.Color(0, 0, 0));
        npm2Label.setText("210711122");

        javax.swing.GroupLayout headerPanelLayout = new javax.swing.GroupLayout(headerPanel);
        headerPanel.setLayout(headerPanelLayout);
        headerPanelLayout.setHorizontalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tenagaMedisPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(rekamMedisPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pasienPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(92, 92, 92)
                .addGroup(headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(kelompokLabel)
                    .addComponent(npmLabel)
                    .addComponent(npm2Label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(titleLabel)
                .addGap(28, 28, 28))
        );
        headerPanelLayout.setVerticalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addGroup(headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(headerPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pasienPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rekamMedisPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tenagaMedisPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(headerPanelLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(titleLabel)
                            .addGroup(headerPanelLayout.createSequentialGroup()
                                .addComponent(kelompokLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)
                                .addComponent(npm2Label)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(npmLabel)))))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        menuPanel.setBackground(new java.awt.Color(148, 180, 159));

        addButton.setBackground(new java.awt.Color(236, 179, 144));
        addButton.setFont(new java.awt.Font("Calisto MT", 1, 12)); // NOI18N
        addButton.setForeground(new java.awt.Color(0, 0, 0));
        addButton.setText("Tambah");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        editButton.setBackground(new java.awt.Color(236, 179, 144));
        editButton.setFont(new java.awt.Font("Calisto MT", 1, 12)); // NOI18N
        editButton.setForeground(new java.awt.Color(0, 0, 0));
        editButton.setText("Ubah");
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });

        deleteButton.setBackground(new java.awt.Color(236, 179, 144));
        deleteButton.setFont(new java.awt.Font("Calisto MT", 1, 12)); // NOI18N
        deleteButton.setForeground(new java.awt.Color(0, 0, 0));
        deleteButton.setText("Hapus");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuPanelLayout = new javax.swing.GroupLayout(menuPanel);
        menuPanel.setLayout(menuPanelLayout);
        menuPanelLayout.setHorizontalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(editButton)
                    .addComponent(deleteButton)
                    .addComponent(addButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        menuPanelLayout.setVerticalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(addButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deleteButton)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        searchPanel.setBackground(new java.awt.Color(148, 180, 159));

        rekamMedisLabel.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        rekamMedisLabel.setForeground(new java.awt.Color(0, 0, 0));
        rekamMedisLabel.setText("Rekam Medis");

        searchButton.setBackground(new java.awt.Color(236, 179, 144));
        searchButton.setFont(new java.awt.Font("Calisto MT", 1, 12)); // NOI18N
        searchButton.setForeground(new java.awt.Color(0, 0, 0));
        searchButton.setText("Cari");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout searchPanelLayout = new javax.swing.GroupLayout(searchPanel);
        searchPanel.setLayout(searchPanelLayout);
        searchPanelLayout.setHorizontalGroup(
            searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchPanelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(rekamMedisLabel)
                .addGap(63, 63, 63)
                .addComponent(searchInput, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(searchButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        searchPanelLayout.setVerticalGroup(
            searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchPanelLayout.createSequentialGroup()
                .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(searchPanelLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(searchInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(searchButton)))
                    .addGroup(searchPanelLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(rekamMedisLabel)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tenagaMedisLabel.setFont(new java.awt.Font("Noto Sans", 0, 12)); // NOI18N
        tenagaMedisLabel.setForeground(new java.awt.Color(0, 0, 0));
        tenagaMedisLabel.setText("Nama Tenaga Medis");

        namaPasienLabel.setFont(new java.awt.Font("Noto Sans", 0, 12)); // NOI18N
        namaPasienLabel.setForeground(new java.awt.Color(0, 0, 0));
        namaPasienLabel.setText("Nama Pasien");

        diagnosaLabel.setFont(new java.awt.Font("Noto Sans", 0, 12)); // NOI18N
        diagnosaLabel.setForeground(new java.awt.Color(0, 0, 0));
        diagnosaLabel.setText("Diagnosa");

        biayaLabel.setFont(new java.awt.Font("Noto Sans", 0, 12)); // NOI18N
        biayaLabel.setForeground(new java.awt.Color(0, 0, 0));
        biayaLabel.setText("Total Biaya");

        tindakanLabel.setFont(new java.awt.Font("Noto Sans", 0, 12)); // NOI18N
        tindakanLabel.setForeground(new java.awt.Color(0, 0, 0));
        tindakanLabel.setText("Tindakan");

        obatCheckBox.setFont(new java.awt.Font("Noto Sans", 0, 12)); // NOI18N
        obatCheckBox.setForeground(new java.awt.Color(0, 0, 0));
        obatCheckBox.setText("Obat");

        suntikCheckBox.setFont(new java.awt.Font("Noto Sans", 0, 12)); // NOI18N
        suntikCheckBox.setForeground(new java.awt.Color(0, 0, 0));
        suntikCheckBox.setText("Suntik");

        konsultasiCheckBox.setFont(new java.awt.Font("Noto Sans", 0, 12)); // NOI18N
        konsultasiCheckBox.setForeground(new java.awt.Color(0, 0, 0));
        konsultasiCheckBox.setText("Konsultasi");

        cancelButton.setBackground(new java.awt.Color(236, 179, 144));
        cancelButton.setFont(new java.awt.Font("Calisto MT", 1, 12)); // NOI18N
        cancelButton.setForeground(new java.awt.Color(0, 0, 0));
        cancelButton.setText("Batal");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        saveButton.setBackground(new java.awt.Color(236, 179, 144));
        saveButton.setFont(new java.awt.Font("Calisto MT", 1, 12)); // NOI18N
        saveButton.setForeground(new java.awt.Color(0, 0, 0));
        saveButton.setText("Simpan");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        tableRekamMedis.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableRekamMedis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableRekamMedisMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableRekamMedis);

        javax.swing.GroupLayout containerPanelLayout = new javax.swing.GroupLayout(containerPanel);
        containerPanel.setLayout(containerPanelLayout);
        containerPanelLayout.setHorizontalGroup(
            containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerPanelLayout.createSequentialGroup()
                .addGroup(containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(containerPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(headerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(containerPanelLayout.createSequentialGroup()
                                .addComponent(menuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(searchPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, containerPanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(saveButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelButton)
                        .addGap(8, 8, 8))
                    .addGroup(containerPanelLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 979, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(containerPanelLayout.createSequentialGroup()
                                .addGroup(containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tenagaMedisLabel)
                                    .addComponent(tenagaMedisDropdown, 0, 200, Short.MAX_VALUE)
                                    .addComponent(namaPasienLabel)
                                    .addComponent(pasienDropdown, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(diagnosaLabel)
                                    .addComponent(diagnosaInput))
                                .addGap(107, 107, 107)
                                .addGroup(containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(biayaLabel)
                                    .addComponent(biayaInput, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tindakanLabel)
                                    .addGroup(containerPanelLayout.createSequentialGroup()
                                        .addComponent(obatCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(suntikCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(konsultasiCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        containerPanelLayout.setVerticalGroup(
            containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(headerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(menuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(searchPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(50, 50, 50)
                .addGroup(containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tenagaMedisLabel)
                    .addComponent(biayaLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tenagaMedisDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(biayaInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namaPasienLabel)
                    .addComponent(tindakanLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pasienDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(obatCheckBox)
                    .addComponent(suntikCheckBox)
                    .addComponent(konsultasiCheckBox))
                .addGap(18, 18, 18)
                .addComponent(diagnosaLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(diagnosaInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButton)
                    .addComponent(saveButton))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jScrollPane2.setViewportView(containerPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tenagaMedisPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tenagaMedisPanelMouseClicked
        TenagaMedisView tmv = new TenagaMedisView();
        this.dispose();
        tmv.setVisible(true);
    }//GEN-LAST:event_tenagaMedisPanelMouseClicked

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        setComponent(true);
        clearText();
        
        action = "Tambah";
        tenagaMedisDropdown.setSelectedIndex(0);
        pasienDropdown.setSelectedIndex(0);
    }//GEN-LAST:event_addButtonActionPerformed

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        setComponent(true);
        action = "Ubah";
    }//GEN-LAST:event_editButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        int getAnswer = JOptionPane.showConfirmDialog(rootPane, "Apakah yakin ingin menghapus data?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
        
        switch (getAnswer) {
            case 0:
                try {
                    rmControl.deleteRekamMedis(selectedId);
                    clearText();
                    showRekamMedis();
                    setComponent(false);
                    setEditDeleteBtn(false);
                    JOptionPane.showMessageDialog(null, " Data berhasil dihapus...");
                } catch (Exception e) {
                    System.out.println("Error : " + e.getMessage());
                }
                break;
            case 1:
                
                break;
        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        setEditDeleteBtn(false);
        setComponent(false);

        try {
            TableRekamMedis rekammedis = rmControl.showRekamMedis(searchInput.getText());
            if (rekammedis.getRowCount() == 0){
                clearText();
                setEditDeleteBtn(false);
                JOptionPane.showConfirmDialog(rootPane, "Data tidak ditemukan", "Konfirmasi", JOptionPane.DEFAULT_OPTION);
            } else {
                tableRekamMedis.setModel(rekammedis);
            }
        } catch(Exception e) {
            System.out.println("Error : " + e.getMessage());
        }
    }//GEN-LAST:event_searchButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        try {
            inputKosongException();
            
            String tindakan = "";
            String tindakan2 = "";
            String tindakan3 = "";

            if (obatCheckBox.isSelected()) {
                tindakan = "Obat, ";
            }
            if (suntikCheckBox.isSelected()) {
                tindakan2 = "Suntik, ";
            }
            if (konsultasiCheckBox.isSelected()) {
                tindakan3 = "Konsultasi, ";
            }
            
            int selectedIndex;
            
            selectedIndex = tenagaMedisDropdown.getSelectedIndex();
            TenagaMedis selectedtm = listTenagaMedis.get(selectedIndex);
            
            selectedIndex = pasienDropdown.getSelectedIndex();
            Pasien selectedp = listPasien.get(selectedIndex);

            if (action.equals("Tambah")){      
                RekamMedis rm = new RekamMedis(selectedId, diagnosaInput.getText(), Float.parseFloat(biayaInput.getText()), tindakan + tindakan2 + tindakan3, selectedtm, selectedp);
                rmControl.insertRekamMedis(rm);
            } else {
                RekamMedis rm = new RekamMedis(selectedId, diagnosaInput.getText(), Float.parseFloat(biayaInput.getText()), tindakan + tindakan2 + tindakan3, selectedtm, selectedp);
                rmControl.updateRekamMedis(rm);
            }
        }catch(InputKosongException e){
            JOptionPane.showMessageDialog(this, e.message());
        }
        clearText();
        showRekamMedis();
        setComponent(false);
        setEditDeleteBtn(false);
    }//GEN-LAST:event_saveButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        setComponent(false);
        setEditDeleteBtn(false);
        clearText();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void tableRekamMedisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableRekamMedisMouseClicked
        int indexTenagaMedis = -1;
        int indexPasien = -1;
        
        setEditDeleteBtn(true);
        
        setComponent(false);
        
        int clickedRow = tableRekamMedis.getSelectedRow();
        TableModel tableModel = tableRekamMedis.getModel();
        
        selectedId = Integer.parseInt(tableModel.getValueAt(clickedRow, 8).toString());
        diagnosaInput.setText(tableModel.getValueAt(clickedRow, 3).toString());
        biayaInput.setText(tableModel.getValueAt(clickedRow, 4).toString());
        
        String tindakan = tableModel.getValueAt(clickedRow, 5).toString();
        
        if (!(tindakan.substring(0, 1).equals(""))) {
            obatCheckBox.setSelected(true);
        }
        if (tindakan.contains("Suntik")) {
            suntikCheckBox.setSelected(true);
        }
        if (tindakan.contains("Konsultasi")) {
            konsultasiCheckBox.setSelected(true);
        }
        
        String id_tenaga_medis = tableModel.getValueAt(clickedRow, 9).toString();
        for (TenagaMedis tenagaMedis : listTenagaMedis) {
            if (tenagaMedis.getIdTenagaMedis().equals(id_tenaga_medis)) {
                indexTenagaMedis = listTenagaMedis.indexOf(tenagaMedis);
            }
        }
        
        tenagaMedisDropdown.setSelectedIndex(indexTenagaMedis);
        
        String id_pasien = tableModel.getValueAt(clickedRow, 10).toString();
        for (Pasien pasien : listPasien) {
            if (pasien.getId() == Integer.parseInt(id_pasien)) {
                indexPasien = listPasien.indexOf(pasien);
            }
        }
        
        pasienDropdown.setSelectedIndex(indexPasien);
    }//GEN-LAST:event_tableRekamMedisMouseClicked

    private void pasienIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pasienIconMouseClicked
        PasienView pv = new PasienView();
        this.dispose();
        pv.setVisible(true);
    }//GEN-LAST:event_pasienIconMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RekamMedisView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RekamMedisView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RekamMedisView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RekamMedisView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RekamMedisView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JTextField biayaInput;
    private javax.swing.JLabel biayaLabel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JPanel containerPanel;
    private javax.swing.JButton deleteButton;
    private javax.swing.JTextField diagnosaInput;
    private javax.swing.JLabel diagnosaLabel;
    private javax.swing.JButton editButton;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel kelompokLabel;
    private javax.swing.JCheckBox konsultasiCheckBox;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JLabel namaPasienLabel;
    private javax.swing.JLabel npm2Label;
    private javax.swing.JLabel npmLabel;
    private javax.swing.JCheckBox obatCheckBox;
    private javax.swing.JComboBox<Pasien> pasienDropdown;
    private javax.swing.JLabel pasienIcon;
    private javax.swing.JLabel pasienIconLabel;
    private javax.swing.JPanel pasienPanel;
    private javax.swing.JLabel rekamMedisIcon;
    private javax.swing.JLabel rekamMedisIconLabel;
    private javax.swing.JLabel rekamMedisLabel;
    private javax.swing.JPanel rekamMedisPanel;
    private javax.swing.JButton saveButton;
    private javax.swing.JButton searchButton;
    private javax.swing.JTextField searchInput;
    private javax.swing.JPanel searchPanel;
    private javax.swing.JCheckBox suntikCheckBox;
    private javax.swing.JTable tableRekamMedis;
    private javax.swing.JComboBox<TenagaMedis> tenagaMedisDropdown;
    private javax.swing.JLabel tenagaMedisIcon;
    private javax.swing.JLabel tenagaMedisIconLabel;
    private javax.swing.JLabel tenagaMedisLabel;
    private javax.swing.JPanel tenagaMedisPanel;
    private javax.swing.JLabel tindakanLabel;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
