package view;

/**
 * Nama : Thessalonica Angelina Meil
 * NPM  : 210711122
 * 
 * Nama : Alexis Divasonda Sigat Ngaing
 * NPM  : 210711407
 */

import control.TenagaMedisControl;
import exception.InputKosongException;
import exception.IdException;
import exception.InputKosongException;
import javax.swing.JOptionPane;
import model.TenagaMedis;

public class TenagaMedisView extends javax.swing.JFrame {
    private TenagaMedisControl tmControl;
    String action = null;
    
    public TenagaMedisView() {
        initComponents();
        setComponent(false);
        setEditDeleteBtn(false); 
        tmControl = new TenagaMedisControl();
        showTenagaMedis();
    }
    
    public void setComponent(boolean value) {
        idInput.setEnabled(value);
        namaInput.setEnabled(value);
        tahunInput.setEnabled(value);
        noTeleponInput.setEnabled(value);
        npaidiInput.setEnabled(value);
        nirappniInput.setEnabled(value);
        
        dokterRadioBtn.setEnabled(value);
        perawatRadioBtn.setEnabled(value);
        
        saveBtn.setEnabled(value);
        cancelBtn.setEnabled(value);
    }
    
    public void setEditDeleteBtn(boolean value) {
        editBtn.setEnabled(value);
        deleteBtn.setEnabled(value);
    }
    
    public void clearText() {
        idInput.setText("");
        namaInput.setText("");
        tahunInput.setText("");
        noTeleponInput.setText("");
        searchInput.setText("");
        npaidiInput.setText("");
        nirappniInput.setText("");
    }
    
    public void showTenagaMedis() {
        System.out.println(tmControl.showDataDokter());
        System.out.println(tmControl.showDataPerawat());
        showDokterTextArea.setText(tmControl.showDataDokter());
        showPerawatTextArea.setText(tmControl.showDataPerawat());
    }
    
    public void inputKosongException() throws InputKosongException {
        if (namaInput.getText().isEmpty() || tahunInput.getText().isEmpty() || noTeleponInput.getText().isEmpty()) {
            throw new InputKosongException();
        }
    }
    
    public void IdException() throws IdException {
        if (!(idInput.getText().length() >= 5 && idInput.getText().length() <= 8)) {
            throw new IdException();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        titleBarPanel = new javax.swing.JPanel();
        rsLabel = new javax.swing.JLabel();
        titleLabel = new javax.swing.JLabel();
        kelompokLabel = new javax.swing.JLabel();
        npm1Label = new javax.swing.JLabel();
        npm2Label = new javax.swing.JLabel();
        containerPanel = new javax.swing.JPanel();
        addBtn = new javax.swing.JButton();
        editBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        containerInputId = new javax.swing.JPanel();
        idLabel = new javax.swing.JLabel();
        idInput = new javax.swing.JTextField();
        containerInputNama = new javax.swing.JPanel();
        namaLabel = new javax.swing.JLabel();
        namaInput = new javax.swing.JTextField();
        containerInputTahunMasuk1 = new javax.swing.JPanel();
        tahunMasukLabel1 = new javax.swing.JLabel();
        tahunInput = new javax.swing.JTextField();
        containerInputNoTeleponMasuk = new javax.swing.JPanel();
        noTeleponMasukLabel = new javax.swing.JLabel();
        noTeleponInput = new javax.swing.JTextField();
        searchBtn = new javax.swing.JButton();
        searchInput = new javax.swing.JTextField();
        dokterPanel = new javax.swing.JPanel();
        npaidiInput = new javax.swing.JTextField();
        dokterRadioBtn = new javax.swing.JRadioButton();
        npaidiLabel = new javax.swing.JLabel();
        perawatPanel = new javax.swing.JPanel();
        nirappniInput = new javax.swing.JTextField();
        perawatRadioBtn = new javax.swing.JRadioButton();
        nirappniLabel = new javax.swing.JLabel();
        cancelBtn = new javax.swing.JButton();
        saveBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        showDokterTextArea = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        showPerawatTextArea = new javax.swing.JTextArea();
        showDokterLabel = new javax.swing.JLabel();
        perawatLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titleBarPanel.setBackground(new java.awt.Color(212, 226, 212));

        rsLabel.setFont(new java.awt.Font("Imprint MT Shadow", 1, 24)); // NOI18N
        rsLabel.setText("RS MEDIKA ATMA");

        titleLabel.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        titleLabel.setText("Object Persistence 1");

        kelompokLabel.setFont(new java.awt.Font("Sitka Small", 0, 14)); // NOI18N
        kelompokLabel.setText("Kelompok 11");

        npm1Label.setFont(new java.awt.Font("Sitka Small", 0, 14)); // NOI18N
        npm1Label.setText("210711407");

        npm2Label.setFont(new java.awt.Font("Sitka Small", 0, 14)); // NOI18N
        npm2Label.setText("210711122");

        javax.swing.GroupLayout titleBarPanelLayout = new javax.swing.GroupLayout(titleBarPanel);
        titleBarPanel.setLayout(titleBarPanelLayout);
        titleBarPanelLayout.setHorizontalGroup(
            titleBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titleBarPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(titleBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(titleBarPanelLayout.createSequentialGroup()
                        .addComponent(titleLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(titleBarPanelLayout.createSequentialGroup()
                        .addComponent(rsLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(titleBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, titleBarPanelLayout.createSequentialGroup()
                                .addComponent(npm1Label)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(npm2Label))
                            .addComponent(kelompokLabel, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        titleBarPanelLayout.setVerticalGroup(
            titleBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, titleBarPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(titleBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(titleBarPanelLayout.createSequentialGroup()
                        .addComponent(rsLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(titleLabel))
                    .addGroup(titleBarPanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(kelompokLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(titleBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(npm2Label)
                            .addComponent(npm1Label))))
                .addGap(33, 33, 33))
        );

        containerPanel.setBackground(new java.awt.Color(252, 248, 232));

        addBtn.setBackground(new java.awt.Color(223, 120, 97));
        addBtn.setFont(new java.awt.Font("Sitka Text", 1, 12)); // NOI18N
        addBtn.setText("Tambah");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        editBtn.setBackground(new java.awt.Color(223, 120, 97));
        editBtn.setFont(new java.awt.Font("Sitka Text", 1, 12)); // NOI18N
        editBtn.setText("Edit");
        editBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBtnActionPerformed(evt);
            }
        });

        deleteBtn.setBackground(new java.awt.Color(223, 120, 97));
        deleteBtn.setFont(new java.awt.Font("Sitka Text", 1, 12)); // NOI18N
        deleteBtn.setText("Hapus");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        containerInputId.setBackground(new java.awt.Color(236, 179, 144));

        idLabel.setFont(new java.awt.Font("Zilla Slab Medium", 0, 12)); // NOI18N
        idLabel.setText("ID Tenaga Medis");

        javax.swing.GroupLayout containerInputIdLayout = new javax.swing.GroupLayout(containerInputId);
        containerInputId.setLayout(containerInputIdLayout);
        containerInputIdLayout.setHorizontalGroup(
            containerInputIdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerInputIdLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(containerInputIdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(containerInputIdLayout.createSequentialGroup()
                        .addComponent(idLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(idInput))
                .addContainerGap())
        );
        containerInputIdLayout.setVerticalGroup(
            containerInputIdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerInputIdLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(idLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(idInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        containerInputNama.setBackground(new java.awt.Color(236, 179, 144));

        namaLabel.setFont(new java.awt.Font("Zilla Slab Medium", 0, 12)); // NOI18N
        namaLabel.setText("Nama Karyawan");

        javax.swing.GroupLayout containerInputNamaLayout = new javax.swing.GroupLayout(containerInputNama);
        containerInputNama.setLayout(containerInputNamaLayout);
        containerInputNamaLayout.setHorizontalGroup(
            containerInputNamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerInputNamaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(containerInputNamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(containerInputNamaLayout.createSequentialGroup()
                        .addComponent(namaLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(namaInput))
                .addContainerGap())
        );
        containerInputNamaLayout.setVerticalGroup(
            containerInputNamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerInputNamaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(namaLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(namaInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        containerInputTahunMasuk1.setBackground(new java.awt.Color(236, 179, 144));

        tahunMasukLabel1.setFont(new java.awt.Font("Zilla Slab Medium", 0, 12)); // NOI18N
        tahunMasukLabel1.setText("Tahun Masuk");

        tahunInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tahunInputActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout containerInputTahunMasuk1Layout = new javax.swing.GroupLayout(containerInputTahunMasuk1);
        containerInputTahunMasuk1.setLayout(containerInputTahunMasuk1Layout);
        containerInputTahunMasuk1Layout.setHorizontalGroup(
            containerInputTahunMasuk1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerInputTahunMasuk1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(containerInputTahunMasuk1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(containerInputTahunMasuk1Layout.createSequentialGroup()
                        .addComponent(tahunMasukLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(tahunInput))
                .addContainerGap())
        );
        containerInputTahunMasuk1Layout.setVerticalGroup(
            containerInputTahunMasuk1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerInputTahunMasuk1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tahunMasukLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tahunInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        containerInputNoTeleponMasuk.setBackground(new java.awt.Color(236, 179, 144));

        noTeleponMasukLabel.setFont(new java.awt.Font("Zilla Slab Medium", 0, 12)); // NOI18N
        noTeleponMasukLabel.setText("Nomor Telepon");

        javax.swing.GroupLayout containerInputNoTeleponMasukLayout = new javax.swing.GroupLayout(containerInputNoTeleponMasuk);
        containerInputNoTeleponMasuk.setLayout(containerInputNoTeleponMasukLayout);
        containerInputNoTeleponMasukLayout.setHorizontalGroup(
            containerInputNoTeleponMasukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerInputNoTeleponMasukLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(containerInputNoTeleponMasukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(containerInputNoTeleponMasukLayout.createSequentialGroup()
                        .addComponent(noTeleponMasukLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(noTeleponInput))
                .addContainerGap())
        );
        containerInputNoTeleponMasukLayout.setVerticalGroup(
            containerInputNoTeleponMasukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerInputNoTeleponMasukLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(noTeleponMasukLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(noTeleponInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        searchBtn.setBackground(new java.awt.Color(223, 120, 97));
        searchBtn.setFont(new java.awt.Font("Sitka Text", 1, 12)); // NOI18N
        searchBtn.setText("Cari");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        searchInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchInputActionPerformed(evt);
            }
        });

        dokterPanel.setBackground(new java.awt.Color(236, 179, 144));

        npaidiInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                npaidiInputActionPerformed(evt);
            }
        });

        buttonGroup1.add(dokterRadioBtn);
        dokterRadioBtn.setFont(new java.awt.Font("Zilla Slab Medium", 0, 12)); // NOI18N
        dokterRadioBtn.setText("Dokter");
        dokterRadioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dokterRadioBtnActionPerformed(evt);
            }
        });

        npaidiLabel.setFont(new java.awt.Font("Zilla Slab Medium", 0, 12)); // NOI18N
        npaidiLabel.setText("NPAIDI");

        javax.swing.GroupLayout dokterPanelLayout = new javax.swing.GroupLayout(dokterPanel);
        dokterPanel.setLayout(dokterPanelLayout);
        dokterPanelLayout.setHorizontalGroup(
            dokterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dokterPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dokterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(npaidiInput, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dokterRadioBtn)
                    .addComponent(npaidiLabel))
                .addContainerGap(11, Short.MAX_VALUE))
        );
        dokterPanelLayout.setVerticalGroup(
            dokterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dokterPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dokterRadioBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(npaidiLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(npaidiInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        perawatPanel.setBackground(new java.awt.Color(236, 179, 144));

        buttonGroup1.add(perawatRadioBtn);
        perawatRadioBtn.setFont(new java.awt.Font("Zilla Slab Medium", 0, 12)); // NOI18N
        perawatRadioBtn.setText("Perawat");
        perawatRadioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                perawatRadioBtnActionPerformed(evt);
            }
        });

        nirappniLabel.setFont(new java.awt.Font("Zilla Slab Medium", 0, 12)); // NOI18N
        nirappniLabel.setText("NIRAPPNI");

        javax.swing.GroupLayout perawatPanelLayout = new javax.swing.GroupLayout(perawatPanel);
        perawatPanel.setLayout(perawatPanelLayout);
        perawatPanelLayout.setHorizontalGroup(
            perawatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(perawatPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(perawatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nirappniInput, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(perawatRadioBtn)
                    .addComponent(nirappniLabel))
                .addContainerGap(11, Short.MAX_VALUE))
        );
        perawatPanelLayout.setVerticalGroup(
            perawatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, perawatPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(perawatRadioBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(nirappniLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nirappniInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        cancelBtn.setBackground(new java.awt.Color(223, 120, 97));
        cancelBtn.setFont(new java.awt.Font("Sitka Text", 1, 12)); // NOI18N
        cancelBtn.setText("Batal");
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        saveBtn.setBackground(new java.awt.Color(223, 120, 97));
        saveBtn.setFont(new java.awt.Font("Sitka Text", 1, 12)); // NOI18N
        saveBtn.setText("Simpan");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        showDokterTextArea.setColumns(20);
        showDokterTextArea.setRows(5);
        jScrollPane1.setViewportView(showDokterTextArea);

        showPerawatTextArea.setColumns(20);
        showPerawatTextArea.setRows(5);
        jScrollPane2.setViewportView(showPerawatTextArea);

        showDokterLabel.setFont(new java.awt.Font("Zilla Slab Medium", 1, 14)); // NOI18N
        showDokterLabel.setText("Data Dokter");

        perawatLabel.setFont(new java.awt.Font("Zilla Slab Medium", 1, 14)); // NOI18N
        perawatLabel.setText("Data Perawat");

        javax.swing.GroupLayout containerPanelLayout = new javax.swing.GroupLayout(containerPanel);
        containerPanel.setLayout(containerPanelLayout);
        containerPanelLayout.setHorizontalGroup(
            containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, containerPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(containerPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(saveBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cancelBtn))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, containerPanelLayout.createSequentialGroup()
                        .addGroup(containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(containerInputId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(containerPanelLayout.createSequentialGroup()
                                .addComponent(addBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(editBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(deleteBtn))
                            .addComponent(containerInputNama, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(containerInputTahunMasuk1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(containerInputNoTeleponMasuk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(containerPanelLayout.createSequentialGroup()
                                .addComponent(searchInput, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(searchBtn))
                            .addComponent(dokterPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(perawatPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(containerPanelLayout.createSequentialGroup()
                        .addGroup(containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(showDokterLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                        .addGroup(containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(perawatLabel)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(19, 19, 19))
        );
        containerPanelLayout.setVerticalGroup(
            containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerPanelLayout.createSequentialGroup()
                .addGroup(containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(containerPanelLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addBtn)
                            .addComponent(editBtn)
                            .addComponent(searchBtn)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, containerPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(deleteBtn, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(searchInput, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(containerPanelLayout.createSequentialGroup()
                        .addComponent(containerInputId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(containerInputNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(containerInputTahunMasuk1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(containerInputNoTeleponMasuk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(containerPanelLayout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(dokterPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(perawatPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelBtn)
                    .addComponent(saveBtn))
                .addGap(17, 17, 17)
                .addGroup(containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(showDokterLabel)
                    .addComponent(perawatLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titleBarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(containerPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(titleBarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(containerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        setComponent(true);
        clearText();
        searchInput.setText("");
        action = "Tambah";
        idInput.setEnabled(false);
    }//GEN-LAST:event_addBtnActionPerformed

    private void searchInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchInputActionPerformed

    private void dokterRadioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dokterRadioBtnActionPerformed
        npaidiInput.setEnabled(true);
        perawatRadioBtn.setSelected(false);
        nirappniInput.setEnabled(false);
        idInput.setText("DTR-" + tmControl.idDokter());
        
        if (!dokterRadioBtn.isSelected()) {
            npaidiInput.setEnabled(false);
        }
    }//GEN-LAST:event_dokterRadioBtnActionPerformed

    private void perawatRadioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_perawatRadioBtnActionPerformed
        nirappniInput.setEnabled(true);
        dokterRadioBtn.setSelected(false);
        npaidiInput.setEnabled(false);
        idInput.setText("PRT-" + tmControl.idPerawat());
        
        if (!perawatRadioBtn.isSelected()) {
            nirappniInput.setEnabled(false);
        }
    }//GEN-LAST:event_perawatRadioBtnActionPerformed
    
    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        try {
            inputKosongException();
            
            TenagaMedis t;
            String jenis = "";
            
            if (action.equals("Tambah")) {
                if (dokterRadioBtn.isSelected()) {
                    t = new TenagaMedis("DTR-" + tmControl.idDokter(), namaInput.getText(), "Dokter", Integer.parseInt(tahunInput.getText()), noTeleponInput.getText(), npaidiInput.getText(), 0);
                    tmControl.insertDataTenagaMedis(t);
                } else {
                    t = new TenagaMedis("PRT-" + tmControl.idPerawat(), namaInput.getText(), "Perawat", Integer.parseInt(tahunInput.getText()), noTeleponInput.getText(), "", Integer.parseInt(nirappniInput.getText()));
                    tmControl.insertDataTenagaMedis(t);
                }
                JOptionPane.showMessageDialog(null, "Berhasil Tambah Data!");
            } else {
                if (idInput.getText().contains("DTR-")) {
                    t = new TenagaMedis(idInput.getText(), namaInput.getText(), "Dokter", Integer.parseInt(tahunInput.getText()), noTeleponInput.getText(), npaidiInput.getText(), 0);
                    tmControl.updateDataTenagaMedis(t, idInput.getText());
                } else {
                    t = new TenagaMedis(idInput.getText(), namaInput.getText(), "Perawat", Integer.parseInt(tahunInput.getText()), noTeleponInput.getText(), "", Integer.parseInt(nirappniInput.getText()));
                    tmControl.updateDataTenagaMedis(t, idInput.getText());
                }
                JOptionPane.showMessageDialog(null, "Berhasil Ubah Data!"); 
                
                editBtn.setEnabled(false);
                deleteBtn.setEnabled(false);
            }
            clearText();
            showTenagaMedis();
            setComponent(false);
            setEditDeleteBtn(false);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Harus Berupa Angka");
        } catch (InputKosongException e) {
            JOptionPane.showMessageDialog(this, e.message());
        } catch(Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_saveBtnActionPerformed

    private void tahunInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tahunInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tahunInputActionPerformed

    private void npaidiInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_npaidiInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_npaidiInputActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        setEditDeleteBtn(true);
        setComponent(false);

        try {
            TenagaMedis tenagamedis = tmControl.searchTenagaMedis(searchInput.getText());
            if (tenagamedis == null) {
                clearText();
                setEditDeleteBtn(false);
                JOptionPane.showConfirmDialog(null, "Data tidak ditemukan [!]", "Konfirmasi", JOptionPane.DEFAULT_OPTION);
            } else {
                idInput.setText(tenagamedis.getIdTenagaMedis());
                namaInput.setText(tenagamedis.getNama());
                tahunInput.setText("" + tenagamedis.getTahunMasuk());
                noTeleponInput.setText(tenagamedis.getNoTelepon());
                npaidiInput.setText(tenagamedis.getNpaidi());
                nirappniInput.setText("" + tenagamedis.getPpni());
                if (npaidiInput.getText().isEmpty()) {
                    perawatRadioBtn.setSelected(true);
//                    dokterRadioBtn.setSelected(false);
                    npaidiInput.setEnabled(false);
                } else {
                    dokterRadioBtn.setSelected(true);
//                    perawatRadioBtn.setSelected(false);
                    nirappniInput.setEnabled(false);
                }
            }
        } catch (Exception e) {
            System.out.println("Error: " + e.getMessage());
        }
    }//GEN-LAST:event_searchBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        int getAnswer = JOptionPane.showConfirmDialog(rootPane, "Apakah yakin ingin menghapus data?", "Konfirmasi", JOptionPane.YES_NO_OPTION);

        if (getAnswer == JOptionPane.YES_OPTION) {
            try {
                tmControl.deleteDataTenagaMedis(idInput.getText());
                clearText();
                showTenagaMedis();
                JOptionPane.showMessageDialog(null, "Data berhasil dihapus...");
            } catch (Exception e) {
                System.err.println("Error : " + e.getMessage());
            }
        } else {
            JOptionPane.showMessageDialog(null, "Data tidak jadi dihapus!");
        }
        editBtn.setEnabled(false);
        deleteBtn.setEnabled(false);
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        setComponent(false);
        setEditDeleteBtn(false);
        clearText();
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void editBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBtnActionPerformed
        setComponent(true);
        idInput.setEnabled(false);
        action = "Ubah";
        
        if (idInput.getText().contains("DTR-")) {
            perawatRadioBtn.setEnabled(false);
            nirappniInput.setEnabled(false);
        } else {
            dokterRadioBtn.setEnabled(false);
            npaidiInput.setEnabled(false);
        }
    }//GEN-LAST:event_editBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TenagaMedisView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TenagaMedisView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TenagaMedisView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TenagaMedisView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TenagaMedisView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JPanel containerInputId;
    private javax.swing.JPanel containerInputNama;
    private javax.swing.JPanel containerInputNoTeleponMasuk;
    private javax.swing.JPanel containerInputTahunMasuk1;
    private javax.swing.JPanel containerPanel;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JPanel dokterPanel;
    private javax.swing.JRadioButton dokterRadioBtn;
    private javax.swing.JButton editBtn;
    private javax.swing.JTextField idInput;
    private javax.swing.JLabel idLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel kelompokLabel;
    private javax.swing.JTextField namaInput;
    private javax.swing.JLabel namaLabel;
    private javax.swing.JTextField nirappniInput;
    private javax.swing.JLabel nirappniLabel;
    private javax.swing.JTextField noTeleponInput;
    private javax.swing.JLabel noTeleponMasukLabel;
    private javax.swing.JTextField npaidiInput;
    private javax.swing.JLabel npaidiLabel;
    private javax.swing.JLabel npm1Label;
    private javax.swing.JLabel npm2Label;
    private javax.swing.JLabel perawatLabel;
    private javax.swing.JPanel perawatPanel;
    private javax.swing.JRadioButton perawatRadioBtn;
    private javax.swing.JLabel rsLabel;
    private javax.swing.JButton saveBtn;
    private javax.swing.JButton searchBtn;
    private javax.swing.JTextField searchInput;
    private javax.swing.JLabel showDokterLabel;
    private javax.swing.JTextArea showDokterTextArea;
    private javax.swing.JTextArea showPerawatTextArea;
    private javax.swing.JTextField tahunInput;
    private javax.swing.JLabel tahunMasukLabel1;
    private javax.swing.JPanel titleBarPanel;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
