package view;

import control.DosenControl;
import control.MataKuliahControl;
import exception.InputKosongException;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import model.Dosen;
import model.MataKuliah;
import table.TableMataKuliah;

public class MataKuliahView extends javax.swing.JFrame {
    private DosenControl dosenControl;
    private MataKuliahControl mataKuliahControl;
    String action = null;
    List<Dosen> listDosen;
    int selectedId = 0;
    
    /**
     * Creates new form MataKuliahView
     */
    public MataKuliahView() {
        initComponents();
        setComponent(false);
        setRadioKelas(false);
        setEditDeleteBtn(false);
        dosenControl = new DosenControl();
        mataKuliahControl = new MataKuliahControl();
        showMataKuliah();
        setActionCommandRadio();
        setDosentoDropdown();
    }
    
    public void setDosentoDropdown() {
        listDosen = dosenControl.showlistDosen();
        for (int i = 0; i < listDosen.size(); i++) {
            dosenDropdown.addItem(listDosen.get(i));
        }
    }
    
    public void setComponent(boolean value) {
        matakuliahInput.setEnabled(value);
        deskripsiInput.setEnabled(value);
        dosenDropdown.setEnabled(value);
        onlineCheckBox.setEnabled(value);
        offlineCheckBox.setEnabled(value);
        
        saveBtn.setEnabled(value);
        cancelBtn.setEnabled(value);
    }
    
    public void setRadioKelas(boolean value) {
        radio3315.setEnabled(value);
        radio3318.setEnabled(value);
        radio3421.setEnabled(value);
        radio3422.setEnabled(value);
    }
    
    public void setEditDeleteBtn(boolean value) {
        editBtn.setEnabled(value);
        deleteBtn.setEnabled(value);
    }
    
    public void clearText(){
        matakuliahInput.setText("");
        deskripsiInput.setText("");
        dosenDropdown.setSelectedItem(ABORT);
        onlineCheckBox.setSelected(false);
        offlineCheckBox.setSelected(false);
        
        ruangKelasGroup.clearSelection();
        searchInput.setText("");
    }
    
    public void setActionCommandRadio() {
        radio3315.setActionCommand("3315");
        radio3318.setActionCommand("3318");
        radio3421.setActionCommand("3421");
        radio3422.setActionCommand("3422");
    }
    
    public void showMataKuliah() {
        tableMataKuliah.setModel(mataKuliahControl.showMataKuliah(""));
    }
    
    public void InputKosongException() throws InputKosongException {
        if (matakuliahInput.getText().isEmpty() || deskripsiInput.getText().isEmpty()
                || dosenDropdown.getSelectedIndex() == -1) {
            throw new InputKosongException();
        }
        
        if (!onlineCheckBox.isSelected() && !offlineCheckBox.isSelected()) {
            throw new InputKosongException();
        }
        
        if (offlineCheckBox.isSelected() && ruangKelasGroup.getSelection() == null) {
            throw new InputKosongException();
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ruangKelasGroup = new javax.swing.ButtonGroup();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        sidebarPanel = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        lecturerPanel = new javax.swing.JPanel();
        lecturerIcon = new javax.swing.JLabel();
        lecturerLabel = new javax.swing.JLabel();
        coursePanel = new javax.swing.JPanel();
        courseIcon = new javax.swing.JLabel();
        courseLabel = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        containerPanel = new javax.swing.JPanel();
        headerPanel = new javax.swing.JPanel();
        titleContent = new javax.swing.JLabel();
        addBtn = new javax.swing.JButton();
        editBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        searchBtn = new javax.swing.JButton();
        searchInput = new javax.swing.JTextField();
        contentPanel = new javax.swing.JPanel();
        mataKuliahLabel = new javax.swing.JLabel();
        matakuliahInput = new javax.swing.JTextField();
        dosenLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        deskripsiInput = new javax.swing.JTextArea();
        dosenDropdown = new javax.swing.JComboBox<>();
        deskripsiLabel = new javax.swing.JLabel();
        metodeLabel = new javax.swing.JLabel();
        onlineCheckBox = new javax.swing.JCheckBox();
        offlineCheckBox = new javax.swing.JCheckBox();
        kelasLabel = new javax.swing.JLabel();
        radio3315 = new javax.swing.JRadioButton();
        radio3318 = new javax.swing.JRadioButton();
        radio3421 = new javax.swing.JRadioButton();
        radio3422 = new javax.swing.JRadioButton();
        saveBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableMataKuliah = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        sidebarPanel.setBackground(new java.awt.Color(22, 52, 122));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/logo.png"))); // NOI18N
        logo.setText("logo");

        lecturerPanel.setBackground(new java.awt.Color(22, 52, 122));
        lecturerPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lecturerPanelMouseClicked(evt);
            }
        });

        lecturerIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons/lecturer.png"))); // NOI18N
        lecturerIcon.setText("lecturer icon");

        lecturerLabel.setFont(new java.awt.Font("MS UI Gothic", 1, 14)); // NOI18N
        lecturerLabel.setForeground(new java.awt.Color(255, 255, 255));
        lecturerLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lecturerLabel.setText("Dosen");

        javax.swing.GroupLayout lecturerPanelLayout = new javax.swing.GroupLayout(lecturerPanel);
        lecturerPanel.setLayout(lecturerPanelLayout);
        lecturerPanelLayout.setHorizontalGroup(
            lecturerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lecturerPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(lecturerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(lecturerPanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lecturerLabel))
                    .addComponent(lecturerIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        lecturerPanelLayout.setVerticalGroup(
            lecturerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lecturerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lecturerIcon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lecturerLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        coursePanel.setBackground(new java.awt.Color(7, 24, 89));

        courseIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons/book.png"))); // NOI18N
        courseIcon.setText("course icon");

        courseLabel.setFont(new java.awt.Font("MS UI Gothic", 1, 14)); // NOI18N
        courseLabel.setForeground(new java.awt.Color(255, 255, 255));
        courseLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        courseLabel.setText("Mata Kuliah");

        javax.swing.GroupLayout coursePanelLayout = new javax.swing.GroupLayout(coursePanel);
        coursePanel.setLayout(coursePanelLayout);
        coursePanelLayout.setHorizontalGroup(
            coursePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(coursePanelLayout.createSequentialGroup()
                .addGroup(coursePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(coursePanelLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(courseLabel))
                    .addGroup(coursePanelLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(courseIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        coursePanelLayout.setVerticalGroup(
            coursePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(coursePanelLayout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(courseIcon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(courseLabel)
                .addContainerGap())
        );

        javax.swing.GroupLayout sidebarPanelLayout = new javax.swing.GroupLayout(sidebarPanel);
        sidebarPanel.setLayout(sidebarPanelLayout);
        sidebarPanelLayout.setHorizontalGroup(
            sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebarPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sidebarPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(coursePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lecturerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(34, 34, 34))
        );
        sidebarPanelLayout.setVerticalGroup(
            sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebarPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logo)
                .addGap(144, 144, 144)
                .addComponent(lecturerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(coursePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane4.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane4.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        containerPanel.setBackground(new java.awt.Color(243, 243, 243));

        headerPanel.setBackground(new java.awt.Color(255, 255, 255));
        headerPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, java.awt.Color.lightGray));

        titleContent.setBackground(new java.awt.Color(0, 0, 0));
        titleContent.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 32)); // NOI18N
        titleContent.setForeground(new java.awt.Color(0, 0, 0));
        titleContent.setText("Mata Kuliah");

        addBtn.setBackground(new java.awt.Color(0, 153, 0));
        addBtn.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 14)); // NOI18N
        addBtn.setForeground(new java.awt.Color(255, 255, 255));
        addBtn.setText("Tambah");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        editBtn.setBackground(new java.awt.Color(236, 168, 30));
        editBtn.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 14)); // NOI18N
        editBtn.setForeground(new java.awt.Color(255, 255, 255));
        editBtn.setText("Ubah");
        editBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBtnActionPerformed(evt);
            }
        });

        deleteBtn.setBackground(new java.awt.Color(153, 0, 0));
        deleteBtn.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 14)); // NOI18N
        deleteBtn.setForeground(new java.awt.Color(255, 255, 255));
        deleteBtn.setText("Hapus");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        searchBtn.setBackground(new java.awt.Color(22, 52, 122));
        searchBtn.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 14)); // NOI18N
        searchBtn.setForeground(new java.awt.Color(255, 255, 255));
        searchBtn.setText("Cari");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        searchInput.setBackground(new java.awt.Color(255, 255, 255));
        searchInput.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        searchInput.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout headerPanelLayout = new javax.swing.GroupLayout(headerPanel);
        headerPanel.setLayout(headerPanelLayout);
        headerPanelLayout.setHorizontalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(headerPanelLayout.createSequentialGroup()
                        .addComponent(titleContent)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(headerPanelLayout.createSequentialGroup()
                        .addComponent(addBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(editBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(searchInput, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchBtn)
                        .addGap(28, 28, 28))))
        );
        headerPanelLayout.setVerticalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(titleContent)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addBtn)
                    .addComponent(editBtn)
                    .addComponent(deleteBtn)
                    .addComponent(searchBtn)
                    .addComponent(searchInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        contentPanel.setBackground(new java.awt.Color(255, 255, 255));
        contentPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, java.awt.Color.lightGray));

        mataKuliahLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        mataKuliahLabel.setForeground(new java.awt.Color(0, 0, 0));
        mataKuliahLabel.setText("Nama Mata Kuliah");

        matakuliahInput.setBackground(new java.awt.Color(255, 255, 255));

        dosenLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        dosenLabel.setForeground(new java.awt.Color(0, 0, 0));
        dosenLabel.setText("Dosen");

        deskripsiInput.setBackground(new java.awt.Color(255, 255, 255));
        deskripsiInput.setColumns(20);
        deskripsiInput.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        deskripsiInput.setRows(5);
        jScrollPane1.setViewportView(deskripsiInput);

        dosenDropdown.setBackground(new java.awt.Color(255, 255, 255));
        dosenDropdown.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        dosenDropdown.setToolTipText("");
        dosenDropdown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dosenDropdownActionPerformed(evt);
            }
        });

        deskripsiLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        deskripsiLabel.setForeground(new java.awt.Color(0, 0, 0));
        deskripsiLabel.setText("Deskripsi");

        metodeLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        metodeLabel.setForeground(new java.awt.Color(0, 0, 0));
        metodeLabel.setText("Metode Pembelajaran");

        onlineCheckBox.setBackground(new java.awt.Color(255, 255, 255));
        onlineCheckBox.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        onlineCheckBox.setForeground(new java.awt.Color(0, 0, 0));
        onlineCheckBox.setText("Online");
        onlineCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onlineCheckBoxActionPerformed(evt);
            }
        });

        offlineCheckBox.setBackground(new java.awt.Color(255, 255, 255));
        offlineCheckBox.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        offlineCheckBox.setForeground(new java.awt.Color(0, 0, 0));
        offlineCheckBox.setText("Offline");
        offlineCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                offlineCheckBoxActionPerformed(evt);
            }
        });

        kelasLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        kelasLabel.setForeground(new java.awt.Color(0, 0, 0));
        kelasLabel.setText("Ruang Kelas");

        radio3315.setBackground(new java.awt.Color(255, 255, 255));
        ruangKelasGroup.add(radio3315);
        radio3315.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        radio3315.setForeground(new java.awt.Color(0, 0, 0));
        radio3315.setText("3315");

        radio3318.setBackground(new java.awt.Color(255, 255, 255));
        ruangKelasGroup.add(radio3318);
        radio3318.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        radio3318.setForeground(new java.awt.Color(0, 0, 0));
        radio3318.setText("3318");

        radio3421.setBackground(new java.awt.Color(255, 255, 255));
        ruangKelasGroup.add(radio3421);
        radio3421.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        radio3421.setForeground(new java.awt.Color(0, 0, 0));
        radio3421.setText("3421");

        radio3422.setBackground(new java.awt.Color(255, 255, 255));
        ruangKelasGroup.add(radio3422);
        radio3422.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        radio3422.setForeground(new java.awt.Color(0, 0, 0));
        radio3422.setText("3422");

        saveBtn.setBackground(new java.awt.Color(22, 52, 122));
        saveBtn.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 14)); // NOI18N
        saveBtn.setForeground(new java.awt.Color(255, 255, 255));
        saveBtn.setText("Simpan");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        cancelBtn.setBackground(new java.awt.Color(153, 0, 0));
        cancelBtn.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 14)); // NOI18N
        cancelBtn.setForeground(new java.awt.Color(255, 255, 255));
        cancelBtn.setText("Batal");
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        tableMataKuliah.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableMataKuliah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMataKuliahMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tableMataKuliah);

        javax.swing.GroupLayout contentPanelLayout = new javax.swing.GroupLayout(contentPanel);
        contentPanel.setLayout(contentPanelLayout);
        contentPanelLayout.setHorizontalGroup(
            contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentPanelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contentPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 824, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 18, Short.MAX_VALUE))
                    .addGroup(contentPanelLayout.createSequentialGroup()
                        .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(deskripsiLabel)
                            .addComponent(dosenLabel)
                            .addComponent(mataKuliahLabel)
                            .addComponent(matakuliahInput)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
                            .addComponent(dosenDropdown, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contentPanelLayout.createSequentialGroup()
                                .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(metodeLabel)
                                    .addGroup(contentPanelLayout.createSequentialGroup()
                                        .addComponent(onlineCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(offlineCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(kelasLabel)
                                    .addComponent(radio3315, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(radio3318, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(radio3421, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(radio3422, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(244, 244, 244))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contentPanelLayout.createSequentialGroup()
                                .addComponent(saveBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cancelBtn)
                                .addGap(17, 17, 17))))))
        );
        contentPanelLayout.setVerticalGroup(
            contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentPanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mataKuliahLabel)
                    .addComponent(metodeLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(matakuliahInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(onlineCheckBox)
                    .addComponent(offlineCheckBox))
                .addGap(18, 18, 18)
                .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deskripsiLabel)
                    .addComponent(kelasLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contentPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(dosenLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dosenDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(contentPanelLayout.createSequentialGroup()
                        .addComponent(radio3315)
                        .addGap(5, 5, 5)
                        .addComponent(radio3318)
                        .addGap(5, 5, 5)
                        .addComponent(radio3421)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radio3422)))
                .addGap(10, 10, 10)
                .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveBtn)
                    .addComponent(cancelBtn))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout containerPanelLayout = new javax.swing.GroupLayout(containerPanel);
        containerPanel.setLayout(containerPanelLayout);
        containerPanelLayout.setHorizontalGroup(
            containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(headerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(contentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        containerPanelLayout.setVerticalGroup(
            containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(headerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(contentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jScrollPane4.setViewportView(containerPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(sidebarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 898, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sidebarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 860, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dosenDropdownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dosenDropdownActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dosenDropdownActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        setComponent(true);
        setRadioKelas(false);
        ruangKelasGroup.clearSelection();
        
        clearText();
        searchInput.setText("");
        action = "Tambah";
        dosenDropdown.setSelectedIndex(0);
    }//GEN-LAST:event_addBtnActionPerformed

    private void lecturerPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lecturerPanelMouseClicked
        DosenView dv = new DosenView();
        this.dispose();
        dv.setVisible(true);
    }//GEN-LAST:event_lecturerPanelMouseClicked

    private void editBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBtnActionPerformed
        setComponent(true);
        action = "Ubah";
        Boolean value = false;
        if (offlineCheckBox.isSelected()) {
            value = true;
        }
        setRadioKelas(value);
    }//GEN-LAST:event_editBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        int getAnswer = JOptionPane.showConfirmDialog(rootPane, "Apakah yakin ingin menghapus data ?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
        switch(getAnswer) {
            case 0:
               try {
                    mataKuliahControl.deleteDataMataKuliah(selectedId);
                    clearText();
                    showMataKuliah();
                    setComponent(false);
                    setRadioKelas(false);
                    setEditDeleteBtn(false);
                    ruangKelasGroup.clearSelection();
                
                } catch (Exception e) {
                    System.out.println("Error : " + e.getMessage());
                }
               break;
               
            case 1:
               
               break;
        }
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        setEditDeleteBtn(false);
        setComponent(false);
        
        try {
            TableMataKuliah matakuliah = mataKuliahControl.showMataKuliah(searchInput.getText());
            if (matakuliah.getRowCount() == 0) {
                clearText();
                setEditDeleteBtn(false);
                JOptionPane.showConfirmDialog(null, "Data tidak ditemukan", "Konfirmasi", JOptionPane.DEFAULT_OPTION);
            } else {
                tableMataKuliah.setModel(matakuliah);
            }
            clearText();
        } catch(Exception e) {
            System.out.println("Error: " + e.getMessage());
        }
    }//GEN-LAST:event_searchBtnActionPerformed

    private void offlineCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_offlineCheckBoxActionPerformed
        Boolean value = false;
        if (offlineCheckBox.isSelected()) {
            value = true;
        }
        setRadioKelas(value);
        ruangKelasGroup.clearSelection();
    }//GEN-LAST:event_offlineCheckBoxActionPerformed

    private void onlineCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onlineCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_onlineCheckBoxActionPerformed

    private void tableMataKuliahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMataKuliahMouseClicked
        int indexDosen = -1;
        setEditDeleteBtn(true);
        
        setComponent(false);
        setRadioKelas(false);
        ruangKelasGroup.clearSelection();
        
        int clickedRow = tableMataKuliah.getSelectedRow();
        TableModel tableModel = tableMataKuliah.getModel();
        
        selectedId = Integer.parseInt(tableModel.getValueAt(clickedRow, 5).toString());
        matakuliahInput.setText(tableModel.getValueAt(clickedRow, 0).toString());
        deskripsiInput.setText(tableModel.getValueAt(clickedRow, 1).toString());
        
        String metodePembelajaran = tableModel.getValueAt(clickedRow, 3).toString();
        
        switch (metodePembelajaran) {
            case "Hybrid":
                onlineCheckBox.setSelected(true);
                offlineCheckBox.setSelected(true);
                break;
                
            case "Online":
                onlineCheckBox.setSelected(true);
                offlineCheckBox.setSelected(false);
                break;
                
            case "Offline":
                onlineCheckBox.setSelected(false);
                offlineCheckBox.setSelected(true);
                break;   
        }
        String ruangKelas = tableModel.getValueAt(clickedRow, 4).toString();
        switch (ruangKelas) {
            case "3315":
                radio3315.setSelected(true);
                break;
                
            case "3318":
                radio3318.setSelected(true);
                break;
                
            case "3421":
                radio3421.setSelected(true);
                break;
                
            case "3422":
                radio3422.setSelected(true);
                break;
        }
        deskripsiInput.setText(tableModel.getValueAt(clickedRow, 1).toString());
        
        String nomor_induk_dosen = tableModel.getValueAt(clickedRow, 6).toString();
        for (Dosen dosen : listDosen) {
            if (dosen.getNomorIndukDosen().equals(nomor_induk_dosen)) {
                indexDosen = listDosen.indexOf(dosen);
            }
        }
        dosenDropdown.setSelectedIndex(indexDosen);
    }//GEN-LAST:event_tableMataKuliahMouseClicked

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        try {
            InputKosongException();
            String metodePembelajaran = "";
            String kelas = "";
            
            int selectedIndex = dosenDropdown.getSelectedIndex();
            Dosen selectedDosen = listDosen.get(selectedIndex);
            
            if (onlineCheckBox.isSelected() && offlineCheckBox.isSelected()) {
                metodePembelajaran = "Hybrid";
                kelas = ruangKelasGroup.getSelection().getActionCommand();
                
            } else if ( onlineCheckBox.isSelected()) {
                metodePembelajaran = "Online";
                kelas = "Online";
            } else {
                metodePembelajaran = "Offline";
                kelas = ruangKelasGroup.getSelection().getActionCommand();
            }
            
            if (action.equals("Tambah")) {
                MataKuliah mk = new MataKuliah(matakuliahInput.getText(), 
                        deskripsiInput.getText(), metodePembelajaran, kelas, selectedDosen);
                mataKuliahControl.insertDataMataKuliah(mk);
                
            } else {
                MataKuliah mk = new MataKuliah(selectedId, matakuliahInput.getText(),
                        deskripsiInput.getText(), metodePembelajaran, kelas, selectedDosen);
                mataKuliahControl.updateDataMataKuliah(mk);
            }
            clearText();
            showMataKuliah();
            setComponent(false);
            setRadioKelas(false);
            ruangKelasGroup.clearSelection();
            
            setEditDeleteBtn(false);
        } catch (InputKosongException e) {
            JOptionPane.showMessageDialog(this, e.message());
        }
    }//GEN-LAST:event_saveBtnActionPerformed

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        setComponent(false);
        setEditDeleteBtn(false);
        clearText();
    }//GEN-LAST:event_cancelBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MataKuliahView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MataKuliahView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MataKuliahView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MataKuliahView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MataKuliahView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JPanel containerPanel;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JLabel courseIcon;
    private javax.swing.JLabel courseLabel;
    private javax.swing.JPanel coursePanel;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JTextArea deskripsiInput;
    private javax.swing.JLabel deskripsiLabel;
    private javax.swing.JComboBox<Dosen> dosenDropdown;
    private javax.swing.JLabel dosenLabel;
    private javax.swing.JButton editBtn;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel kelasLabel;
    private javax.swing.JLabel lecturerIcon;
    private javax.swing.JLabel lecturerLabel;
    private javax.swing.JPanel lecturerPanel;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel mataKuliahLabel;
    private javax.swing.JTextField matakuliahInput;
    private javax.swing.JLabel metodeLabel;
    private javax.swing.JCheckBox offlineCheckBox;
    private javax.swing.JCheckBox onlineCheckBox;
    private javax.swing.JRadioButton radio3315;
    private javax.swing.JRadioButton radio3318;
    private javax.swing.JRadioButton radio3421;
    private javax.swing.JRadioButton radio3422;
    private javax.swing.ButtonGroup ruangKelasGroup;
    private javax.swing.JButton saveBtn;
    private javax.swing.JButton searchBtn;
    private javax.swing.JTextField searchInput;
    private javax.swing.JPanel sidebarPanel;
    private javax.swing.JTable tableMataKuliah;
    private javax.swing.JLabel titleContent;
    // End of variables declaration//GEN-END:variables
}
